// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJWOLZLyamae9auw-L1NghMdn1xbIAkqs',
    appId: '1:689574214729:web:3f7c88cef2ee1bc1c11398',
    messagingSenderId: '689574214729',
    projectId: 'swe444-suhail',
    authDomain: 'swe444-suhail.firebaseapp.com',
    storageBucket: 'swe444-suhail.appspot.com',
    measurementId: 'G-X76JL9SS0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7x8W1a7RTWkucntEumc4XQ1DVmx6SHq0',
    appId: '1:689574214729:android:ce35d0c94a5fb959c11398',
    messagingSenderId: '689574214729',
    projectId: 'swe444-suhail',
    storageBucket: 'swe444-suhail.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC867e4e9PFXfQ3hEpZklq-4AliRptlji0',
    appId: '1:689574214729:ios:277dea85a6a32e86c11398',
    messagingSenderId: '689574214729',
    projectId: 'swe444-suhail',
    storageBucket: 'swe444-suhail.appspot.com',
    iosClientId: '689574214729-fkh4cotjb07hj0uirko8mab46pnfgntm.apps.googleusercontent.com',
    iosBundleId: 'com.example.suhailProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC867e4e9PFXfQ3hEpZklq-4AliRptlji0',
    appId: '1:689574214729:ios:289180372c6768c9c11398',
    messagingSenderId: '689574214729',
    projectId: 'swe444-suhail',
    storageBucket: 'swe444-suhail.appspot.com',
    iosClientId: '689574214729-ssbtai6col2c4tpijj166072g8s0ihh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.suhailProject.RunnerTests',
  );
}
